# ==== App bundle ====
AppBundle:
    type: rest
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /v1/
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc